- name: Install | Add i386 architecture
  become: false
  command: dpkg --add-architecture i386

- name: Install | (lib32) Packages
  become: false
  apt:
    name: lib32gcc1
    update_cache: true

- name: accept steam license
  become: false
  debconf:
    name: "steam"
    question: "steam/question"
    value: "I AGREE"
    vtype: "select"

- name: Install SteamCMD
  become: false
  apt:
    name: steamcmd
    update_cache: yes

- name: Install zomboid dedicated server via SteamCMD
  command: "steamcmd +login anonymous +force_install_dir {{zomboid_server_dir}} +app_update 380870 validate +quit"
  register: zomboid_install

- name: Print zomboid install result
  debug: var=zomboid_install.stdout_lines
